### ISSUE TITLE
Volatility camparison

### ISSUE THREAD

**Issue by Titotix** [BromiumLabs/PackerAttacker#6]
Hey !
I am evaluating this project to use it. And in this way, I was wondering the differences from this product to Volatility (used with malfind, dlllist...) ? Did you already use Volatility this way ? Did you already face some unhooked code injection with your product ?
In theorical feature, it's similar. Your product is more automatic btw.

**Comment by vadimkotov** [comment]
Hello there,

You're quite right! This tool is made for automated hidden code extraction at scale. Compared to Volatility its capabilities are limited and narrowly focused on payload extraction from malware droppers.
Currently we haven't tested it specifically against hooking-aware malware, but this is definitely on our roadmap.
